-- MySQL Script generated by MySQL Workbench
-- Sat Nov 10 10:50:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema milani
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema milani
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `milani` DEFAULT CHARACTER SET utf8 ;
USE `milani` ;

-- -----------------------------------------------------
-- Table `milani`.`tblUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblUsers` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nameUser` VARCHAR(30) NOT NULL,
  `pswUser` VARCHAR(30) NOT NULL,
  `activeUser` TINYINT(1) NOT NULL,
  `profileUser` VARCHAR(15) NOT NULL,
  `emailUser` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idtblUsers_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `nameusuario_UNIQUE` (`nameUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblClients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblClients` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nameClient` VARCHAR(50) NOT NULL,
  `aliasClient` VARCHAR(20) NULL,
  `cdcClient` VARCHAR(14) NOT NULL,
  `ieClient` VARCHAR(12) NULL,
  `extcodeClient` INT NULL,
  `freightClient` DECIMAL(15,2) NULL,
  `discClient` DECIMAL(3,2) NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `cdcclient_UNIQUE` (`cdcClient` ASC) VISIBLE,
  UNIQUE INDEX `ieclient_UNIQUE` (`ieClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblSuppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblSuppliers` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `nameSupplier` VARCHAR(50) NOT NULL,
  `aliasSupplier` VARCHAR(20) NULL,
  `cdcSupplier` VARCHAR(14) NULL,
  `ieSupplier` VARCHAR(12) NULL,
  `extcodeSupplier` VARCHAR(15) NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblAddressType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblAddressType` (
  `idAddressType` INT NOT NULL AUTO_INCREMENT,
  `descAddressType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAddressType`),
  UNIQUE INDEX `nomeAddressType_UNIQUE` (`descAddressType` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblClientAddresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblClientAddresses` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `id_Client` INT NOT NULL,
  `id_AddressType` INT NOT NULL,
  `addressClient` VARCHAR(80) NOT NULL,
  `numberClient` VARCHAR(6) NOT NULL,
  `complClient` VARCHAR(20) NULL,
  `distrClient` VARCHAR(20) NOT NULL,
  `ufClient` VARCHAR(2) NOT NULL,
  `cityClient` VARCHAR(60) NOT NULL,
  `cepClient` VARCHAR(8) NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `FK_ClientAddresses_Clients_idx` (`id_Client` ASC) VISIBLE,
  INDEX `FK_ClientAddresses_AddressType_idx` (`id_AddressType` ASC) VISIBLE,
  CONSTRAINT `FK_ClientAddresses_Clients`
    FOREIGN KEY (`id_Client`)
    REFERENCES `milani`.`tblClients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ClientAddresses_AddressType`
    FOREIGN KEY (`id_AddressType`)
    REFERENCES `milani`.`tblAddressType` (`idAddressType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblContactType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblContactType` (
  `idContactType` INT NOT NULL AUTO_INCREMENT,
  `descContactType` VARCHAR(45) NULL,
  `nameContact` VARCHAR(45) NULL,
  PRIMARY KEY (`idContactType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tbSupplierAdresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tbSupplierAdresses` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `id_Supplier` INT NOT NULL,
  `id_AddressType` INT NOT NULL,
  `addressSupplier` VARCHAR(80) NOT NULL,
  `numberSupplier` VARCHAR(6) NOT NULL,
  `complSupplier` VARCHAR(20) NULL,
  `distSupplier` VARCHAR(20) NOT NULL,
  `ufSupplier` VARCHAR(2) NOT NULL,
  `citySupplier` VARCHAR(60) NOT NULL,
  `cepSupplier` VARCHAR(8) NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `FK_SupplierAdresses_Supplier_idx` (`id_Supplier` ASC) VISIBLE,
  INDEX `FK_SupplierAddresses_AddressType_idx` (`id_AddressType` ASC) VISIBLE,
  CONSTRAINT `FK_SupplierAdresses_Supplier`
    FOREIGN KEY (`id_Supplier`)
    REFERENCES `milani`.`tblSuppliers` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SupplierAddresses_AddressType`
    FOREIGN KEY (`id_AddressType`)
    REFERENCES `milani`.`tblAddressType` (`idAddressType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblClientContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblClientContact` (
  `idlClientContact` INT NOT NULL AUTO_INCREMENT,
  `id_Client` INT NOT NULL,
  `id_ContactType` INT NOT NULL,
  `emailClient` VARCHAR(50) NULL,
  `phClient` VARCHAR(10) NULL,
  `mbClient` VARCHAR(11) NULL,
  PRIMARY KEY (`idlClientContact`),
  INDEX `FK_ClientContact_Clients_idx` (`id_Client` ASC) VISIBLE,
  INDEX `FK_ClientContact_ContactType_idx` (`id_ContactType` ASC) VISIBLE,
  CONSTRAINT `FK_ClientContact_Clients`
    FOREIGN KEY (`id_Client`)
    REFERENCES `milani`.`tblClients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ClientContact_ContactType`
    FOREIGN KEY (`id_ContactType`)
    REFERENCES `milani`.`tblContactType` (`idContactType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblProducts` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `cdProduct` VARCHAR(10) NOT NULL,
  `descProduct` VARCHAR(20) NOT NULL,
  `clrProduct` VARCHAR(8) NOT NULL,
  `sizeProduct` VARCHAR(15) NOT NULL,
  `extcodeProduct` VARCHAR(10) NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `cdProduct_UNIQUE` (`cdProduct` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblPackage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblPackage` (
  `idPackage` INT NOT NULL AUTO_INCREMENT,
  `cdPackage` VARCHAR(10) NOT NULL,
  `descPackage` VARCHAR(20) NOT NULL,
  `volPackage` INT NOT NULL,
  PRIMARY KEY (`idPackage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblStateProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblStateProduct` (
  `idStateProduct` INT NOT NULL AUTO_INCREMENT,
  `descStateProduct` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idStateProduct`),
  UNIQUE INDEX `descStateProduct_UNIQUE` (`descStateProduct` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblLocalStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblLocalStock` (
  `idLocalStock` INT NOT NULL,
  `descLocalStock` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idLocalStock`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblStockMov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblStockMov` (
  `idStockMov` INT NOT NULL AUTO_INCREMENT,
  `dateStockMov` DATETIME NOT NULL,
  `id_Product` INT NOT NULL,
  `id_StateProduct` INT NOT NULL,
  `id_Package` INT NOT NULL,
  `id_StockLocal` INT NOT NULL,
  `qtdStockMov` DECIMAL(7,2) NOT NULL,
  `descLote` VARCHAR(10) NULL,
  `id_mov` INT NULL,
  `tpmov` VARCHAR(8) NULL COMMENT 'Inserir constraint CHECK para valores: INTERNO, PRODUCAO ou SPOT',
  PRIMARY KEY (`idStockMov`),
  INDEX `FK_StockMov_Products_idx` (`id_Product` ASC) VISIBLE,
  INDEX `FK_StockMov_StateProduct_idx` (`id_StateProduct` ASC) VISIBLE,
  INDEX `FK_StockMov_Packages_idx` (`id_Package` ASC) VISIBLE,
  INDEX `FK_StockMov_LocalStock_idx` (`id_StockLocal` ASC) INVISIBLE,
  CONSTRAINT `FK_StockMov_Products`
    FOREIGN KEY (`id_Product`)
    REFERENCES `milani`.`tblProducts` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_StockMov_StateProduct`
    FOREIGN KEY (`id_StateProduct`)
    REFERENCES `milani`.`tblStateProduct` (`idStateProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_StockMov_Package`
    FOREIGN KEY (`id_Package`)
    REFERENCES `milani`.`tblPackage` (`idPackage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_StockMov_LocalStock`
    FOREIGN KEY (`id_StockLocal`)
    REFERENCES `milani`.`tblLocalStock` (`idLocalStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblQueueOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblQueueOrders` (
  `idQueueOrder` INT NOT NULL AUTO_INCREMENT,
  `id_Product` INT NOT NULL,
  `id_Package` INT NOT NULL,
  `dateQueue` DATETIME NOT NULL,
  `amtOrder` DECIMAL(7,2) NOT NULL,
  `stsOrder` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idQueueOrder`),
  INDEX `FK_QueueOrders_Products_idx` (`id_Product` ASC) VISIBLE,
  INDEX `FK_QueueOrders_Package_idx` (`id_Package` ASC) VISIBLE,
  CONSTRAINT `FK_QueueOrders_Products`
    FOREIGN KEY (`id_Product`)
    REFERENCES `milani`.`tblProducts` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_QueueOrders_Package`
    FOREIGN KEY (`id_Package`)
    REFERENCES `milani`.`tblPackage` (`idPackage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblOrders` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `id_Client` INT NOT NULL,
  `orderDate` DATETIME NOT NULL,
  `statusOrder` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `FK_Orders_Clients_idx` (`id_Client` ASC) VISIBLE,
  CONSTRAINT `FK_Orders_Clients`
    FOREIGN KEY (`id_Client`)
    REFERENCES `milani`.`tblClients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblOrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblOrderDetails` (
  `idOrderDetail` INT NOT NULL AUTO_INCREMENT,
  `id_Order` INT NOT NULL,
  `id_Product` INT NOT NULL,
  `id_Package` INT NOT NULL,
  `unitPrice` DECIMAL(7,2) NOT NULL,
  `quantityOrder` TINYINT NOT NULL,
  `discountOrder` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`idOrderDetail`),
  INDEX `FK_OrderDetails_Orders_idx` (`id_Order` ASC) VISIBLE,
  INDEX `FK_OrderDetails_Products_idx` (`id_Product` ASC) VISIBLE,
  INDEX `FK_OrderDetails_Package_idx` (`id_Package` ASC) VISIBLE,
  CONSTRAINT `FK_OrderDetails_Orders`
    FOREIGN KEY (`id_Order`)
    REFERENCES `milani`.`tblOrders` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OrderDetails_Products`
    FOREIGN KEY (`id_Product`)
    REFERENCES `milani`.`tblProducts` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OrderDetails_Package`
    FOREIGN KEY (`id_Package`)
    REFERENCES `milani`.`tblPackage` (`idPackage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblProduction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblProduction` (
  `idProduction` INT NOT NULL AUTO_INCREMENT,
  `dateProduction` DATETIME NOT NULL,
  `statusProduction` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idProduction`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `milani`.`tblProductionItens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblProductionItens` (
  `idProductionItens` INT NOT NULL AUTO_INCREMENT,
  `id_Production` INT NOT NULL,
  `id_Order` INT NULL,
  `id_Product` INT NOT NULL,
  `id_Package` INT NOT NULL,
  `id_StateProduct` INT NOT NULL,
  `quantityItem` INT NOT NULL,
  PRIMARY KEY (`idProductionItens`),
  INDEX `FK_ProductionItens_Production_idx` (`id_Production` ASC) VISIBLE,
  INDEX `Fk_ProductionItens_Orders_idx` (`id_Order` ASC) VISIBLE,
  INDEX `FK_ProductionItens_Product_idx` (`id_Product` ASC) VISIBLE,
  INDEX `FK_ProductionItens_Package_idx` (`id_Package` ASC) VISIBLE,
  INDEX `FK_ProductionItens_StateProducts_idx` (`id_StateProduct` ASC) VISIBLE,
  CONSTRAINT `FK_ProductionItens_Production`
    FOREIGN KEY (`id_Production`)
    REFERENCES `milani`.`tblProduction` (`idProduction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_ProductionItens_Orders`
    FOREIGN KEY (`id_Order`)
    REFERENCES `milani`.`tblOrders` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ProductionItens_Product`
    FOREIGN KEY (`id_Product`)
    REFERENCES `milani`.`tblProducts` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ProductionItens_Package`
    FOREIGN KEY (`id_Package`)
    REFERENCES `milani`.`tblPackage` (`idPackage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ProductionItens_StateProduct`
    FOREIGN KEY (`id_StateProduct`)
    REFERENCES `milani`.`tblStateProduct` (`idStateProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milani`.`tblSpotSales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblSpotSales` (
  `idSpotSales` INT NOT NULL,
  `id_Client` INT NOT NULL,
  `id_Product` INT NOT NULL,
  `id_Package` INT NOT NULL,
  `unitPrice` DECIMAL(5,2) NOT NULL,
  `quantity` TINYINT NOT NULL,
  PRIMARY KEY (`idSpotSales`),
  INDEX `FK_SpotSales_Clients_idx` (`id_Client` ASC) VISIBLE,
  INDEX `FK_SpotSales_Products_idx` (`id_Product` ASC) VISIBLE,
  INDEX `FK_SpotSales_Package_idx` (`id_Package` ASC) VISIBLE,
  CONSTRAINT `FK_SpotSales_Clients`
    FOREIGN KEY (`id_Client`)
    REFERENCES `milani`.`tblClients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SpotSales_Products`
    FOREIGN KEY (`id_Product`)
    REFERENCES `milani`.`tblProducts` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SpotSales_Package`
    FOREIGN KEY (`id_Package`)
    REFERENCES `milani`.`tblPackage` (`idPackage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*tblSpotSales TRIGGERS*/
DELIMITER $
CREATE DEFINER = CURRENT_USER TRIGGER `milani`.`tblSpotSales_AFTER_INSERT` AFTER INSERT ON `tblSpotSales` FOR EACH ROW
BEGIN
	INSERT INTO tblStockMov VALUES(now(), NEW.id_Product, 1, NEW.id_Package, 1, NEW.quantity, NULL, NEW.idSpotSales, 'SPOT');
    /*PARAMETROS PASSADOS: DATA DA VENDA, ID PRODUTO, ESTADO DO PRODUTO = 1 (MADURO),
	  ID DA CAIXA, LOCAL DE ARMAZENAMENTO = 1 (PÁTIO), QUANTIDADE VENDIDA, Codigo Lote = NULL,
      ID DO MOVIMENTO = ID DA VENDA, E TIPO DO REGISTRO = 'SPOT'*/
END$
DELIMITER ;
DELIMITER $
CREATE DEFINER = CURRENT_USER TRIGGER `milani`.`tblSpotSales_AFTER_DELETE` AFTER DELETE ON `tblSpotSales` FOR EACH ROW
BEGIN
	DELETE FROM tblStockMov
    WHERE idmov=OLD.idSpotSales AND tpmov='SPOT';
END$
DELIMITER ;

-- -----------------------------------------------------
-- Table `milani`.`tblPackageStorage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milani`.`tblPackageStorage` (
  `idPackageStorage` INT NOT NULL AUTO_INCREMENT,
  `id_Package` INT NULL,
  `id_Client` INT NULL,
  `id_Supplier` INT NULL,
  `id_LocalStock` INT NULL,
  `quantityPackage` INT NOT NULL,
  `dateStorage` DATETIME NOT NULL,
  PRIMARY KEY (`idPackageStorage`),
  INDEX `FK_PackageStorage_Package_idx` (`id_Package` ASC) VISIBLE,
  INDEX `FK_PackageStorage_Clients_idx` (`id_Client` ASC) VISIBLE,
  INDEX `FK_PackageStorage_Supplier_idx` (`id_Supplier` ASC) VISIBLE,
  INDEX `FK_PackageStorage_LocalStock_idx` (`id_LocalStock` ASC) VISIBLE,
  CONSTRAINT `FK_PackageStorage_Package`
    FOREIGN KEY (`id_Package`)
    REFERENCES `milani`.`tblPackage` (`idPackage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PackageStorage_Clients`
    FOREIGN KEY (`id_Client`)
    REFERENCES `milani`.`tblClients` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PackageStorage_Supplier`
    FOREIGN KEY (`id_Supplier`)
    REFERENCES `milani`.`tblSuppliers` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PackageStorage_LocalStock`
    FOREIGN KEY (`id_LocalStock`)
    REFERENCES `milani`.`tblLocalStock` (`idLocalStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
