DELIMITER $
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`tblSpotSales_AFTER_DELETE` AFTER DELETE ON `tblSpotSales` FOR EACH ROW
BEGIN
	DELETE FROM tblStockMov
    WHERE idmov=OLD.idSpotSales AND tpmov='SPOT';
END$
DELIMITER ;